<?php
declare(strict_types=1);
require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'chat_auth.php';
if(!meso_chat_is_authorized()&&!meso_chat_set_authorized_cookie()){http_response_code(503);header('Content-Type: text/plain; charset=utf-8');echo 'Meso Voice Lab is unavailable.';exit;}
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; media-src 'self'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'; form-action 'none'");
header('Cache-Control: no-store, private');header('Referrer-Policy: no-referrer');header('X-Content-Type-Options: nosniff');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Meso Voice Lab v2.2</title>
<style>:root{color-scheme:dark;--bg:#0b0e14;--card:#141924;--line:#2b3344;--text:#f3f5f8;--muted:#9ba5b7;--accent:#9dd1ff;--bad:#ff8f8f}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}.wrap{max-width:900px;margin:auto;padding:22px 15px 48px}header{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-bottom:18px}h1{font-size:23px;margin:0}.sub,.hint,.status{color:var(--muted)}.badge{border:1px solid var(--line);border-radius:999px;padding:7px 10px;color:var(--accent);white-space:nowrap}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:16px;margin:14px 0}.batch{font-weight:800;font-size:18px}.phrase{font-size:18px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.play,.choose,.nav,.reject{min-height:46px;border-radius:11px;border:1px solid var(--line);background:#1c2331;color:var(--text);font-weight:750;cursor:pointer}.play.active,.choose.active{outline:2px solid var(--accent);border-color:transparent}.play[disabled],.nav[disabled]{opacity:.45;cursor:wait}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:14px}.actions>*{flex:1}.reject{border-color:#633;color:var(--bad)}select{width:100%;margin:8px 0 14px;background:#10151f;color:var(--text);border:1px solid var(--line);border-radius:10px;padding:11px}.status{margin-top:12px;min-height:22px}a{color:var(--accent)}@media(max-width:620px){header{flex-direction:column}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.grid .play:last-child,.grid .choose:last-child{grid-column:span 2}}</style></head><body>
<div class="wrap"><header><div><h1>Meso Voice Discovery Sweep</h1><div class="sub">One reference at a time. Five anonymous candidates per batch. Reject weak batches immediately.</div></div><div class="badge">Voice v2.2</div></header>
<section class="card"><div class="batch">Batch <span data-batch>1</span> of <span data-batch-count>?</span></div><div class="hint">Every letter in a batch uses exactly one private Meso reference.</div>
<label for="phrase">Test phrase</label><select id="phrase"><option value="ar-casual">Arabic · casual</option><option value="ar-warm">Arabic · warm</option><option value="en-casual">English · casual</option></select>
<div class="phrase" data-phrase-text dir="rtl">مرحبا، كيفك اليوم؟ شو أخبارك؟ خبرني شو صار معك.</div>
<div class="grid" data-plays><button class="play" type="button" data-label="A">A</button><button class="play" type="button" data-label="B">B</button><button class="play" type="button" data-label="C">C</button><button class="play" type="button" data-label="D">D</button><button class="play" type="button" data-label="E">E</button></div>
<div class="status" data-status>Listen to all five, then choose the closest voice or reject the batch.</div>
<div class="grid" data-choices><button class="choose" type="button" data-choice="A">Choose A</button><button class="choose" type="button" data-choice="B">Choose B</button><button class="choose" type="button" data-choice="C">Choose C</button><button class="choose" type="button" data-choice="D">Choose D</button><button class="choose" type="button" data-choice="E">Choose E</button></div>
<div class="actions"><button class="reject" type="button" data-reject>Reject all</button><button class="nav" type="button" data-prev>Previous batch</button><button class="nav" type="button" data-next>Next batch</button></div></section>
<div class="hint">The source identities stay hidden. Production Meso Voice v2 is not changed by this lab. · <a href="/meso/chat/">Back to chat</a></div></div>
<script src="/meso/voice-lab/voice-lab.js?v=22" defer></script></body></html>
