<?php declare(strict_types=1); ?>
<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="referrer" content="no-referrer"><meta name="robots" content="noindex,nofollow,noarchive">
<title>MesoAI Private Import</title>
<style>
:root{color-scheme:dark;--bg:#08090e;--panel:#11141d;--line:#2a3040;--txt:#f5f6fa;--muted:#969dae;--accent:#b58cff;--good:#63dda9;--bad:#ff8f8f}*{box-sizing:border-box}body{margin:0;min-height:100dvh;background:radial-gradient(circle at 50% -10%,#281d3c,#0a0c12 38%,var(--bg));font:15px/1.45 system-ui,-apple-system,Segoe UI,Roboto,Arial;color:var(--txt);display:grid;place-items:center;padding:20px}.box{width:min(620px,100%);border:1px solid var(--line);background:rgba(17,20,29,.94);border-radius:24px;padding:24px;box-shadow:0 28px 90px #0008}.brand{font-size:14px;color:var(--accent);font-weight:800}.box h1{font-size:30px;letter-spacing:-.035em;margin:8px 0 8px}.box p{color:var(--muted);margin:0 0 20px}.drop{border:1px dashed #485168;border-radius:18px;padding:22px;text-align:center;background:#0c0f17}input{width:100%;margin-top:12px}.btn{margin-top:16px;width:100%;height:48px;border:0;border-radius:15px;background:linear-gradient(135deg,#d8b4fe,#8b5cf6);font-weight:850;color:#111;cursor:pointer}.btn:disabled{opacity:.45;cursor:not-allowed}.progress{height:9px;border-radius:99px;background:#242938;overflow:hidden;margin-top:18px}.bar{height:100%;width:0;background:linear-gradient(90deg,#d8b4fe,#8b5cf6);transition:width .15s}.status{margin-top:12px;color:var(--muted);min-height:44px}.ok{color:var(--good)}.bad{color:var(--bad)}code{font-size:12px;color:#c8cee0}.fine{font-size:12px;color:#747c8e;margin-top:18px}
</style></head><body><main class="box">
<div class="brand">MesoAI · PRIVATE LOCAL IMPORT</div><h1>Import reference pack</h1>
<p>This page transfers the already-filtered voice reference pack directly to MASTER-PC. The pack is never placed in the public web directory.</p>
<div class="drop"><strong>Expected file</strong><br><code>MesoAI-private-reference-pack.zip</code><input id="file" type="file" accept=".zip,application/zip"></div>
<button id="send" class="btn" disabled>Import to MASTER-PC</button><div class="progress"><div id="bar" class="bar"></div></div><div id="status" class="status">Waiting for the reference pack.</div>
<div class="fine">One-time token · 512 KB chunks · final size and SHA-256 verification · token deleted after success</div>
</main><script>
const EXPECTED_SIZE=13532599;
const EXPECTED_SHA='411e478f9d9eac93f5f0a428b58a9b0cd7cee34300e5ba9065a40bebcb77251b';
const params=new URLSearchParams(location.search); const token=params.get('token')||'';
history.replaceState({},document.title,location.pathname);
const file=document.getElementById('file'),send=document.getElementById('send'),bar=document.getElementById('bar'),statusEl=document.getElementById('status');
if(!token){statusEl.textContent='This private import link is missing its one-time token.';statusEl.className='status bad';}
file.addEventListener('change',()=>{const f=file.files[0];send.disabled=!token||!f;statusEl.className='status';if(!f)return;if(f.name!=='MesoAI-private-reference-pack.zip') statusEl.textContent='Select the MesoAI private reference pack ZIP.';else if(f.size!==EXPECTED_SIZE) statusEl.textContent='File size does not match the prepared reference pack.';else statusEl.textContent='Reference pack ready to import.';});
function hex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
send.addEventListener('click',async()=>{const f=file.files[0];if(!f||!token)return;if(f.name!=='MesoAI-private-reference-pack.zip'||f.size!==EXPECTED_SIZE){statusEl.textContent='Wrong reference pack.';statusEl.className='status bad';return}send.disabled=true;try{statusEl.textContent='Verifying local file…';const digest=hex(await crypto.subtle.digest('SHA-256',await f.arrayBuffer()));if(digest!==EXPECTED_SHA)throw new Error('SHA-256 does not match the prepared pack');const chunkSize=512*1024,count=Math.ceil(f.size/chunkSize);const uploadId=crypto.randomUUID().replaceAll('-','');for(let i=0;i<count;i++){const body=f.slice(i*chunkSize,Math.min(f.size,(i+1)*chunkSize));const r=await fetch('api/private-upload.php',{method:'POST',headers:{'X-Meso-Token':token,'X-Meso-Upload-Id':uploadId,'X-Meso-Sha256':EXPECTED_SHA,'X-Meso-Chunk-Index':String(i),'X-Meso-Chunk-Count':String(count),'X-Meso-Total-Bytes':String(f.size)},body});const j=await r.json().catch(()=>({ok:false,error:'invalid server response'}));if(!r.ok||!j.ok)throw new Error(j.error||('HTTP '+r.status));bar.style.width=Math.round(((i+1)/count)*100)+'%';statusEl.textContent=`Uploading privately… ${i+1}/${count}`;if(i===count-1&&!j.complete)throw new Error('server did not finalize upload')}statusEl.textContent='Reference pack verified and stored on MASTER-PC. Upload token is now closed.';statusEl.className='status ok';}catch(e){statusEl.textContent='Import failed: '+e.message;statusEl.className='status bad';send.disabled=false;}});
</script></body></html>
